### ISSUE TITLE
Arrowhead Management Tool installation blocked by Windows Defender

### ISSUE THREAD

**Issue by fiedorjan** [Aitia-IIOT/arrowhead-tools-aitia#40]
When I try to install the Arrowhead Management Tool using the Arrowhead-Management-Tool-Setup-2.0.0.exe installer on Windows 10, Windows Defender detects Trojan:Win32/Wacatac.H!ml in the installer, blocks the installation, and deletes the installer.

**Comment by borditamas** [comment]
Dear @fiedorjan,
check please the [FAQ & Known issues](https://github.com/Aitia-IIOT/arrowhead-tools-aitia/issues/35) for the reason and solution.

**Comment by fiedorjan** [comment]
OK, thank you. The description and solution in the FAQ is not very convincing though. Do you know why Windows Defender is detecting this type of Trojan in the installer and not, e.g., in the certificate generator? If Defender is always detecting this kind of Trojan, you should explicitly state it in the FAQ so users know what to expect. Moreover, explanation why Defender may think there is a Trojan in the installer would also be helpful.

**Comment by borditamas** [comment]
@fiedorjan Thanks for your feedback. The FAQ has been updated with more details.
